mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - ./data/mongo:/data/db

quokka:
    restart: always
    image: quokka/quokkadev
    working_dir: /quokka
    ports:
        - "5000"
    dns:
        - "8.8.8.8"
        - "8.8.4.4"
    volumes:
        - ./quokka:/quokka
        - ./media:/quokka/quokka/mediafiles
        - ./themes/material:/quokka/quokka/themes/material
    links:
        - mongo:mongo
    command: python manage.py runserver --host 0.0.0.0 --reloader --debug
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - QUOKKA_MONGODB_DB=papodestartup
        - QUOKKA_DEFAULT_THEME=material
    mem_limit: 1000000000
