mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - ./data/mongo:/data/db

quokka:
    restart: always
    image: quokka/quokkadev
    working_dir: /quokka
    ports:
        - "5000"
    volumes:
        - ./quokka:/quokka
    links:
        - mongo:mongo
    command: cp local_settings.py quokka/quokka/ && sh quokka/etc/docker_wait_to_start.sh
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - WAIT_COMMAND=$(nc -zv mongo 27017)
        - WAIT_START_CMD=python manage.py runserver --host 0.0.0.0 --reloader --debug
        - WAIT_SLEEP=3
        - WAIT_LOOPS=50
    mem_limit: 1000000000
