mongo:
    image: mongo
    ports:
      - "27017"
    volumes:
      - ./data/mongo:/data/db

quokka:
    restart: always
    image: quokka/quokkadev
    working_dir: /quokka
    ports:
        - "5000"
    volumes:
        - ./quokka:/quokka
    links:
        - mongo:mongo
    command: python manage.py runserver --host 0.0.0.0 --reloader --debug
    environment:
        - QUOKKA_MONGODB_HOST=mongo
        - QUOKKA_MONGODB_DB=papodestartup
    mem_limit: 1000000000
